### ISSUE TITLE
iOS deployment Target

### ISSUE THREAD

**Issue by wuftymerguftyguff** [NeoTeo/SwiftBase58#1]
iOS deployment target for SwiftBase58 (and SwiftGMP and SwiftHex) are defaulting to latest iOS when added by carthage.

This prevents it from being used with projects with an earlier deployment target.

I can fix this buy changing the projects that carthage downloads and running a manual build but it is a real pain.

As dynamic frameworks are supported after iOS 8 it would make sense to set the iOS deployment target for all your carthage based frameworks to the lowest possible iOS target.  

Thanks

**Comment by NeoTeo** [comment]
Good point, thanks. 
I have been meaning to update the whole stack of libs using this but kind of holding out for Swift 3. 
I will change this as soon as I have a bit of time though.

**Comment by NeoTeo** [comment]
Version 0.4.1 should do it.
